services:
  backend:
    container_name: app-nestjs
    build: .
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    container_name: db-postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: {}
